// Loader/parser for the compact binary star catalog (apps/web/public/stars.v1.bin,
// generated by scripts/build_star_catalog.py — format "NSK1" documented there).
// Parsed once into typed arrays sized for the renderer's hot loops.

export interface StarCatalog {
  n: number
  /** Right ascension in radians. */
  raRad: Float32Array
  sinDec: Float32Array
  cosDec: Float32Array
  /** Visual magnitude, ascending (brightest first — file order). */
  mag: Float32Array
  /** B−V quantized to 16 color bins (0 = bluest, 15 = reddest). */
  colorBin: Uint8Array
  /** Star indices sorted by (colorBin, mag) for batched drawing. */
  order: Uint16Array
  /** binStart[b]..binStart[b+1] is the `order` range of color bin b (length 17). */
  binStart: number[]
  /** Proper names of the brightest stars, keyed by record index. */
  names: Map<number, string>
}

export const COLOR_BINS = 16
const MAGIC = 0x314b534e // "NSK1" little-endian
const HEADER_BYTES = 16
const RECORD_BYTES = 8

export function parseCatalog(buf: ArrayBuffer): StarCatalog {
  const dv = new DataView(buf)
  if (dv.getUint32(0, true) !== MAGIC) throw new Error('stars.bin: bad magic')
  const version = dv.getUint16(4, true)
  const recordSize = dv.getUint16(6, true)
  if (version !== 1 || recordSize !== RECORD_BYTES) {
    throw new Error(`stars.bin: unsupported version ${version}/recordSize ${recordSize}`)
  }
  const n = dv.getUint32(8, true)
  const namesOffset = dv.getUint32(12, true)

  const raRad = new Float32Array(n)
  const sinDec = new Float32Array(n)
  const cosDec = new Float32Array(n)
  const mag = new Float32Array(n)
  const colorBin = new Uint8Array(n)

  const RA_SCALE = (Math.PI * 2) / 65535
  const DEC_SCALE = (Math.PI / 2) / 32767
  for (let i = 0; i < n; i++) {
    const off = HEADER_BYTES + i * RECORD_BYTES
    raRad[i] = dv.getUint16(off, true) * RA_SCALE
    const dec = dv.getInt16(off + 2, true) * DEC_SCALE
    sinDec[i] = Math.sin(dec)
    cosDec[i] = Math.cos(dec)
    mag[i] = dv.getInt16(off + 4, true) / 100
    colorBin[i] = Math.min(COLOR_BINS - 1, dv.getUint8(off + 6) >> 4)
  }

  // Bucket by color bin, preserving magnitude order within each bin (records are
  // mag-sorted), so the renderer can set fillStyle once per bin and stop early
  // per bin when the limiting magnitude is reached.
  const counts = new Array<number>(COLOR_BINS).fill(0)
  for (let i = 0; i < n; i++) counts[colorBin[i]]++
  const binStart = new Array<number>(COLOR_BINS + 1).fill(0)
  for (let b = 0; b < COLOR_BINS; b++) binStart[b + 1] = binStart[b] + counts[b]
  const cursor = binStart.slice(0, COLOR_BINS)
  const order = new Uint16Array(n)
  for (let i = 0; i < n; i++) order[cursor[colorBin[i]]++] = i

  const namesArr = JSON.parse(
    new TextDecoder().decode(new Uint8Array(buf, namesOffset)),
  ) as [number, string][]

  return { n, raRad, sinDec, cosDec, mag, colorBin, order, binStart, names: new Map(namesArr) }
}

let catalogPromise: Promise<StarCatalog> | null = null

/** Fetch + parse the star catalog once per session (module-level cache). */
export function loadCatalog(): Promise<StarCatalog> {
  if (!catalogPromise) {
    catalogPromise = fetch(`${import.meta.env.BASE_URL}stars.v1.bin`)
      .then(r => {
        if (!r.ok) throw new Error(`stars.v1.bin: HTTP ${r.status}`)
        return r.arrayBuffer()
      })
      .then(parseCatalog)
      .catch(err => {
        catalogPromise = null // allow a retry on the next mount
        throw err
      })
  }
  return catalogPromise
}
