"""Operator-controlled runtime feature flags — storage only.

A small DynamoDB table that lets an operator turn an individual feature off or
back on without a code change or redeploy (see darkhours/feature_flags.py for
the read side). Deployed manually, on its own — this stack must never become a
dependency of the CI-deployed PyNightSkyLambda stack, mirroring the same
lifecycle-decoupling already used for the provider-health table.

No Lambda lives here: the only writers are an operator's own AWS credentials
(see scripts/local-flags/, not checked in); the API/Worker Lambdas only ever
get a read-only grant, wired in from lambda_api_stack.py.
"""
from aws_cdk import (
    Stack,
    CfnOutput,
    RemovalPolicy,
    Tags,
    aws_dynamodb as dynamodb,
)
from constructs import Construct


class FeatureFlagsStack(Stack):
    def __init__(self, scope: Construct, cid: str, **kwargs):
        super().__init__(scope, cid, **kwargs)

        Tags.of(self).add("Project", "pynightsky")
        Tags.of(self).add("Env", "prod")
        Tags.of(self).add("Component", "feature-flags")

        table = dynamodb.Table(
            self, "FeatureFlagsTable",
            partition_key=dynamodb.Attribute(name="flag_id", type=dynamodb.AttributeType.STRING),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            # Operator-set state, not regenerated by anything — unlike the provider-health
            # table (rebuilt every 5 min), this must survive a stack replacement.
            removal_policy=RemovalPolicy.RETAIN,
        )

        # Plain stack output for an operator to read off the console/CLI and hand to the
        # PyNightSkyLambda stack as the PYNIGHTSKY_FEATURE_FLAGS_TABLE secret — NOT a
        # CloudFormation Export (see lambda_api_stack.py: that would couple these two
        # independently-deployed stacks' lifecycles).
        CfnOutput(self, "FeatureFlagsTableName", value=table.table_name)
